//
// GetUserGroupsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserGroupsResponse: Codable {

    public var userGroups: [UserGroup]

    public init(userGroups: [UserGroup]) {
        self.userGroups = userGroups
    }


}
