//
// GroupListGroups.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Group Info. */

public struct GroupListGroups: Codable {

    /** Unique group ID. */
    public var groupId: String
    public var userIds: [String]
    public var userNames: [String]

    public init(groupId: String, userIds: [String], userNames: [String]) {
        self.groupId = groupId
        self.userIds = userIds
        self.userNames = userNames
    }

    public enum CodingKeys: String, CodingKey { 
        case groupId
        case userIds = "user_ids"
        case userNames = "user_names"
    }

}
