//
// GroupList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupList: Codable {

    public var groups: [GroupListGroups]

    public init(groups: [GroupListGroups]) {
        self.groups = groups
    }


}
