//
// HealthcheckResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HealthcheckResponse: Codable {

    public enum Healthcheck: String, Codable { 
        case success = "success"
        case fail = "fail"
    }
    public var healthcheck: Healthcheck?

    public init(healthcheck: Healthcheck? = nil) {
        self.healthcheck = healthcheck
    }


}
