//
// LikeResponseGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** If it is a mutual like, this property is expected. */

public struct LikeResponseGroup: Codable {

    public var groupIds: [String]
    public var userIds: [String]
    public var userNames: [String]

    public init(groupIds: [String], userIds: [String], userNames: [String]) {
        self.groupIds = groupIds
        self.userIds = userIds
        self.userNames = userNames
    }

    public enum CodingKeys: String, CodingKey { 
        case groupIds = "group_ids"
        case userIds = "user_ids"
        case userNames = "user_names"
    }

}
