//
// LikeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LikeResponse: Codable {

    public var mutualLike: Bool
    public var group: LikeResponseGroup?

    public init(mutualLike: Bool, group: LikeResponseGroup? = nil) {
        self.mutualLike = mutualLike
        self.group = group
    }

    public enum CodingKeys: String, CodingKey { 
        case mutualLike = "mutual_like"
        case group
    }

}
