//
// PreferredAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PreferredAttributes: Codable {

    public enum Gender: String, Codable { 
        case male = "male"
        case female = "female"
        case other = "other"
    }
    public enum FoodPreference: String, Codable { 
        case vegetarian = "Vegetarian"
        case vegan = "Vegan"
        case jain = "Jain"
        case glutenFree = "Gluten-Free"
        case noPreference = "No Preference"
    }
    public enum SleepSchedule: String, Codable { 
        case earlyBird = "early_bird"
        case nightOwl = "night_owl"
        case somewhereInBetween = "somewhere_in_between"
    }
    /** User&#x27;s gender */
    public var gender: Gender?
    /** User&#x27;s hobbies or interests */
    public var hobbies: [String]?
    /** User&#x27;s food preference */
    public var foodPreference: FoodPreference?
    /** User&#x27;s cleanliness rating (1&#x3D;very messy, 5&#x3D;very clean) */
    public var cleanliness: Int?
    /** User&#x27;s preferred sleep schedule */
    public var sleepSchedule: SleepSchedule?
    /** Whether the user smokes or not */
    public var smoking: Bool?
    /** Whether the user likes to party or not */
    public var partying: Bool?
    /** Whether the user is okay with living with pets or not */
    public var petFriendly: Bool?

    public init(gender: Gender? = nil, hobbies: [String]? = nil, foodPreference: FoodPreference? = nil, cleanliness: Int? = nil, sleepSchedule: SleepSchedule? = nil, smoking: Bool? = nil, partying: Bool? = nil, petFriendly: Bool? = nil) {
        self.gender = gender
        self.hobbies = hobbies
        self.foodPreference = foodPreference
        self.cleanliness = cleanliness
        self.sleepSchedule = sleepSchedule
        self.smoking = smoking
        self.partying = partying
        self.petFriendly = petFriendly
    }

    public enum CodingKeys: String, CodingKey { 
        case gender
        case hobbies
        case foodPreference = "food_preference"
        case cleanliness
        case sleepSchedule = "sleep_schedule"
        case smoking
        case partying
        case petFriendly = "pet_friendly"
    }

}
