//
// UserAttributesCoverImages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAttributesCoverImages: Codable {

    public var imageUrl: String?

    public init(imageUrl: String? = nil) {
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case imageUrl = "image_url"
    }

}
