//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var userId: String?
    public var email: String?
    /** If user has joined any group, it will represent it&#x27;s group id. */
    public var groupId: String?
    public var userAttributes: UserAttributes?
    public var preferredAttributes: PreferredAttributes?

    public init(userId: String? = nil, email: String? = nil, groupId: String? = nil, userAttributes: UserAttributes? = nil, preferredAttributes: PreferredAttributes? = nil) {
        self.userId = userId
        self.email = email
        self.groupId = groupId
        self.userAttributes = userAttributes
        self.preferredAttributes = preferredAttributes
    }

    public enum CodingKeys: String, CodingKey { 
        case userId
        case email
        case groupId
        case userAttributes = "user_attributes"
        case preferredAttributes = "preferred_attributes"
    }

}
