//
// UserGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserGroup: Codable {

    /** Unique group ID. */
    public var groupId: String?
    public var groupInfo: String?
    public var userCount: Int?
    public var userIds: [String]?
    public var users: [User]?

    public init(groupId: String? = nil, groupInfo: String? = nil, userCount: Int? = nil, userIds: [String]? = nil, users: [User]? = nil) {
        self.groupId = groupId
        self.groupInfo = groupInfo
        self.userCount = userCount
        self.userIds = userIds
        self.users = users
    }

    public enum CodingKeys: String, CodingKey { 
        case groupId
        case groupInfo = "group_info"
        case userCount = "user_count"
        case userIds = "user_ids"
        case users
    }

}
