//
// UserCreatedResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserCreatedResponse: Codable {

    /** ID of the user upon creation. */
    public var userId: String

    public init(userId: String) {
        self.userId = userId
    }


}
